<a href="https://colab.research.google.com/github/ByeonJaeseong/DeepLearningProject/blob/main/grade_cut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
import tensorflow as tf
from tensorflow import keras
uploaded = files.upload()

Saving percentage_of_correct_answers.cell to percentage_of_correct_answers.cell
Saving percentage_of_correct_answers_modi.cell to percentage_of_correct_answers_modi.cell


In [20]:
# 데이터 업로드
df_data = pd.read_excel('percentage_of_correct_answers_modi.cell', index_col=0)
df_data.head()
df_data.describe()

0           1           2           3           4           5   \
count  291.000000  291.000000  291.000000  291.000000  291.000000  291.000000   
mean    91.701031   94.343643   90.453608   88.941581   91.017182   86.257732   
std      4.023633   44.084231    4.640944    5.302572   47.212393    7.369946   
min     71.000000   77.000000   66.000000   66.000000   58.000000   56.000000   
25%     90.000000   90.000000   88.000000   87.000000   86.000000   84.000000   
50%     92.000000   93.000000   92.000000   90.000000   89.000000   88.000000   
75%     95.000000   94.500000   94.000000   92.000000   92.000000   91.000000   
max     98.000000  841.000000   98.000000   97.000000  888.000000   97.000000   

               6           7           8           9   ...         20  \
count  291.000000  291.000000  291.000000  291.000000  ...  291.00000   
mean    84.962199   82.965636   84.632302   80.271478  ...   43.00000   
std      8.006158    8.630271   46.971512    9.282084  ...   12.87687   
min     33.000000   38.000000   54.000000   50.000000  ...   12.00000   
25%     82.000000   79.000000   78.000000   77.000000  ...   34.00000   
50%     87.000000   85.000000   84.000000   82.000000  ...   42.00000   
75%     90.500000   89.000000   88.000000   87.000000  ...   51.00000   
max     96.000000   96.000000  870.000000   96.000000  ...   84.00000   

               21          22          23          24          25          26  \
count  291.000000  291.000000  291.000000  291.000000  291.000000  291.000000   
mean    86.199313   81.195876   74.845361   69.333333   56.068729   45.793814   
std      6.220223   10.723136   12.499109   13.544393   17.522855   18.726860   
min     58.000000   32.000000   29.000000   22.000000    8.000000    3.000000   
25%     83.000000   77.000000   68.500000   60.500000   45.000000   32.000000   
50%     88.000000   84.000000   78.000000   71.000000   59.000000   46.000000   
75%     91.000000   89.000000   84.000000   80.000000   69.000000   61.000000   
max     96.000000   95.000000   94.000000   92.000000   89.000000   87.000000   

               27          28          29  
count  291.000000  291.000000  291.000000  
mean    40.134021   25.408935   14.151203  
std     16.768379   15.211196   12.725666  
min      7.000000    4.000000    0.000000  
25%     27.000000   14.000000    6.000000  
50%     39.000000   22.000000   10.000000  
75%     51.500000   34.000000   18.000000  
max     82.000000   79.000000  100.000000  

[8 rows x 30 columns]

In [21]:
# 타겟 데이터 업로드
df_target = pd.read_excel('grade_cut_modi.cell', index_col=0)
df_target.head()



0    1    2    3    4   5   6   7   8
0  151  138  128  118  103  89  81  79  75
1  158  138  128  118  103  89  81  79  75
2  157  138  128  118  103  89  81  79  75
3  145  133  126  119  107  91  80  76  72
4  145  133  126  119  107  91  80  76  72

In [22]:
df_main = pd.concat([df_data, df_target], axis=1) # concatenate # data 합치기
df_main.head()

0   1   2   3   4   5   6   7   8   9   ...  29   0    1    2    3    4   \
0  85  90  78  87  70  64  91  64  73  89  ...   1  151  138  128  118  103   
1  95  96  93  96  87  79  94  84  88  82  ...   7  158  138  128  118  103   
2  89  91  84  88  78  74  89  75  80  80  ...   6  157  138  128  118  103   
3  82  80  79  85  80  60  82  80  60  77  ...   5  145  133  126  119  107   
4  95  95  95  89  95  81  78  95  84  87  ...  10  145  133  126  119  107   

   5   6   7   8   
0  89  81  79  75  
1  89  81  79  75  
2  89  81  79  75  
3  91  80  76  72  
4  91  80  76  72  

[5 rows x 39 columns]

In [38]:
percentage_data = np.array(df_data)
grade_cut = np.array(df_target)
pd.DataFrame(percentage_data)
data_X = percentage_data[:]
data_Y = grade_cut[:]
print(data_X.shape)
print(data_X)
print(data_Y.shape)
print(data_Y)


(291, 30)
[[85 90 78 ... 38 16  1]
 [95 96 93 ... 31  8  7]
 [89 91 84 ... 33 15  6]
 ...
 [85 86 85 ... 42 63  7]
 [89 90 90 ... 74 50 33]
 [87 82 85 ... 40 26 48]]
(291, 9)
[[151 138 128 ...  81  79  75]
 [158 138 128 ...  81  79  75]
 [157 138 128 ...  81  79  75]
 ...
 [155 141 129 ...  83  78  74]
 [141 138 130 ...  82  76  73]
 [156 141 127 ...  83  78  72]]


In [40]:
from sklearn import model_selection

x_train, x_test, y_train, y_test = model_selection.train_test_split(percentage_data, grade_cut, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(232, 30)
(59, 30)
(232, 9)
(59, 9)
